### ISSUE TITLE
Operador - Cambios 

### ISSUE THREAD

**Issue by fanky10** [fanky10/sep-bas#51]
Si no tiene jugadores por los que realizar cambio, aparece el modal pero sin un mensaje ni nada. Definir que hacer en tal caso

**Comment by pablonife** [comment]
Para mi está bien que aparezca así ... la consola debe ser lo más flexible posible a mi entender , con un escape se vuelve rápido ...

**Comment by fanky10** [comment]
Quedamos que le ponemos un boton cancelar.
