### ISSUE TITLE
Lista de partidos

### ISSUE THREAD

**Issue by fanky10** [fanky10/sep-bas#56]
La lista de partidos en una simple tabla donde te deje ver el informe.

Partido (local vs visitante)
Juez (arbitro)
Fecha (fecha partido | ver ficha)

**Comment by pablonife** [comment]
Debería verse más que un partido ? tener en cuenta que es un ambiente distribuido el operador y no contendrá todos los partidos sino los que se jugaron en un club ... por ejemplo todos los partidos que jugo fisherton

**Comment by fanky10** [comment]
pushed and merged into milestone-1.3
